### ISSUE TITLE
TypeError: 'float' object cannot be interpreted as an integer

### ISSUE THREAD

**Issue by drsagitn** [avolkov1/keras_experiments#14]
Line 125, mnist_tfrecord_mgpu.py causing float type error

`steps_per_epoch = train_samples / batch_size`

Should change to

`steps_per_epoch = train_samples // batch_size`

**Comment by avolkov1** [comment]
Thanks, I'll update the code.

**Comment by avolkov1** [comment]
Fixed in commit 6856b9e.
