### ISSUE TITLE
ImportError: No module named keras_frcnn

### ISSUE THREAD

**Issue by bzamecnik** [avolkov1/keras_experiments#4]
```
$ PYTHONPATH=. CUDA_VISIBLE_DEVICES=3 python examples/faster_rcnn/train_frcnn_mgpu.py --epochs=4
Using TensorFlow backend.
Traceback (most recent call last):
  File "examples/faster_rcnn/train_frcnn_mgpu.py", line 21, in <module>
    from keras_frcnn import config, data_generators
ImportError: No module named keras_frcnn
```

It implicitly assumes that https://github.com/yhenon/keras-frcnn is installed and available for import.

**Comment by avolkov1** [comment]
@bzamecnik Yes, exactly. I'm not going to copy all the code from keras-frcnn. At the top of [train_frcnn_mgpu.py](https://github.com/avolkov1/keras_experiments/blob/master/examples/faster_rcnn/train_frcnn_mgpu.py) I commented:
```
# Based on: https://github.com/yhenon/keras-frcnn/blob/master/train_frcnn.py
# Clone repo: https://github.com/yhenon/keras-frcnn
# add this example into the repo with keras_exp in the PYTHONPATH and run.
# python train_frcnn_mgpu.py -p /path/to/pascalvoc
```

I added this example for illustration with issue #3. The reporter there wanted to run `train_frcnn.py` with multiple GPUs. That example is not so simple run with multiple GPUs. I fixed a bug dealing with multiple outputs not being handled correctly, but the other issues have nothing to do with multigpu logic code. Refer to my explanation here: [explanation](https://github.com/avolkov1/keras_experiments/issues/3#issuecomment-321945105).

**Comment by bzamecnik** [comment]
OK. Thanks for info.
