### ISSUE TITLE
ModelTFRecordMixin.fit_tfrecord() - num_train_samples is wrong

### ISSUE THREAD

**Issue by bzamecnik** [avolkov1/keras_experiments#6]
```num_train_samples = steps_per_epoch```
should be fixed to:

```num_train_samples = steps_per_epoch * batch_size```

otherwise we divide by `batch_size` twice.

Eg. in the MNIST model for 60000 samples and batch_size 128 we end up with `4 = ceil(60000 / 128 / 128)` batches.

**Comment by avolkov1** [comment]
@bzamecnik Thank you. I think you are correct. The mixin fit_tfrecord logic was based on the _fit_loop logic here:
[https://github.com/ahundt/keras/blob/2e214c436e18c488ed5cb86e45dc67610f32e952/keras/engine/training.py](https://github.com/ahundt/keras/blob/2e214c436e18c488ed5cb86e45dc67610f32e952/keras/engine/training.py)

I need to update the mnist tfrecord example to incorporate Keras 2.0.7 updates. This mixin seems unecessary with the Keras 2.0.7 updates and I'll just get rid of the mixin as I might have more bugs in it. [Keras 2.0.7](https://github.com/fchollet/keras/releases/tag/2.0.7)

**Comment by avolkov1** [comment]
@bzamecnik I updated the `mnist_tfrecrod_mgpu.py` example in commit [555e8bf](https://github.com/avolkov1/keras_experiments/commit/555e8bf3c32784e154ef13cdc8a3fa2c7e29b13d). Let me know if that doesn't seem right. I tested and it seems to work pretty well. The example updates require upgrading to Keras 2.0.8 (I think 2.0.7 should work too but I didn't test).

**Comment by bzamecnik** [comment]
@avolkov1 Thanks! I thought I can make a PR, but was too busy this week. I'll continue on the project probably on Friday so I can test your changes.

**Comment by bzamecnik** [comment]
The code seems to work properly in this regard. Thanks.
