### ISSUE TITLE
Saving the model

### ISSUE THREAD

**Issue by dhimanpd** [avolkov1/keras_experiments#7]
Hi,
How can I save the model definition?
Can you provide some info on how to save the model definition and reload model using json and load_weights. 
I am getting an exception when saving model definition.

**Comment by avolkov1** [comment]
@dhimanpd Can you post the traceback? You should be able to save weights from the multigpu parallelized model. Load weights during serial model defintion. Refer to `def make_model_full` in the `cifar10_cnn_mgpu.py` examples. Save the multigpu model's weights either by using a callback or save_weights after training.

Load the weights into the serial model. Also, for json save the serial_model's json. Then load it, and parallelize it with make_parallel. Saving weights from the parallelized multigpu model should work, if not please post the traceback and maybe a snippet of your code logic (parts where you load/save json and weights).
